name: re_dash
description: A ClojureDart framework for building user interfaces, leveraging Flutter
version: 1.2.1

environment:
  sdk: ^3.0.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
