(ns hti.re-dash-test
  (:require [clojure.test :refer [deftest is testing]]
            [hti.re-dash :refer [build-sub-map]]))

(deftest build-sub-map-test
  (binding [hti.re-dash/app-db (atom {:foo {:bar 42} :baz 9001})]
    (testing "Two functions case"
      ;; (reg-sub ::foo (fn [_ _]) (fn [_ _]))
      (let [input-fn #()
            comp-fn #()]
        (is (= {:signal-fn input-fn :computation-fn comp-fn}
               (build-sub-map (list input-fn comp-fn))))))))
