(ns acme.main
  (:require ["package:flutter/material.dart" :as m]
            [cljd.flutter :as f]
            [acme.model :as model]
            [acme.view :as view]))

(defn main []

  (model/register!)

  (f/run
    (m/MaterialApp
      .title "Welcome to Flutter"
      .theme (m/ThemeData .primarySwatch m.Colors/blue))
    .home
    (m/Scaffold
      .appBar (m/AppBar
                .title (m/Text "ClojureDart with a splash of re-dash")))
    .body
    m/Center
    view/albums))
