(ns acme.model
  (:require [hti.re-dash.core :as rd]))

(defn register!
  []

  (rd/reg-event-fx
   ::count
   (fn [{:keys [db]} _]
     (let [current-count (inc (:current-count db 0))]
       {:db (assoc db :current-count current-count)
        ::log-count current-count})))

  (rd/reg-sub
   ::get-count
   (fn [db _]
     (:current-count db)))

  (rd/reg-fx
   ::log-count
   (fn [current-count]
     (println (str "The current-count is " current-count)))))
