name: fetch

description: Shows an example of data fetching from an HTTP endpoint, using effects. A spinner indicates that an HTTP request is in flight.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  re_dash:
    path: .clojuredart/deps/9e731771ee44667e14d1ef770e035e356b959692944310a4eb0a6918f52e5a6c

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
