name: CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.1'
        channel: 'stable'

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        cli: '1.11.1.1208'
        bb: '1.3.179'

    - name: Test
      run: bb test
